# Copyright (c) 2016-2017 Martin Donath <martin.donath@squidfunk.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Project information
site_name: Material Design Components for MkDocs
site_description: A Material Design Components theme for MkDocs
site_author: Joshua Burnett
site_url: http://9ci.github.io/mkdocs-material-components/

# Repository
repo_name: 9ci/mkdocs-material-components
repo_url: https://github.com/9ci/mkdocs-material-components
edit_uri: edit/master/docs/

# Copyright
# copyright: 'Copyright &copy; 2016 - 2017 Martin Donath'

# Theme directory
theme_dir: material

# Options
extra:
  # use console.log(btoa('some-password')) in chrome console to generate.
  # If this is set js will force a div overlay over all the page content.
  # this is NOT security. A user can always just use the debubg console and remove the overlay div or just look at the html source for the page

  # adds <meta name="robots" content="noindex,nofollow"> to keep search engines from indexing this
  # noindex: true
  feature:
    tabs: false
  palette:
    primary: 'blue grey'
    accent: indigo
  social:
    - type: globe
      link: http://struct.cc
    - type: github-alt
      link: https://github.com/9ci
    - type: twitter
      link: https://twitter.com/9ci
    - type: linkedin
      link: https://de.linkedin.com/in/greenbill

# Extensions
markdown_extensions:
  - pymdownx.extra # replacement for markdown.extensions.extra see https://facelessuser.github.io/pymdown-extensions/extensions/extra/
  - markdown.extensions.admonition
  - markdown.extensions.codehilite(guess_lang=false)
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc(permalink=true)
  - markdown_include.include:
      base_path: 'docs'
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      #emoji_generator: !!python/name:pymdownx.emoji.to_svg
      emoji_index: !!python/name:pymdownx.emoji.gemoji
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde

# Page tree
pages:
  - Index: index.md
  - Syntax Quick Start: sandbox.md
  - Embedding web apps:
    - Excel: embedding/excel.md
    - Lucid Charts: embedding/lucid.md
    - Evernote: embedding/evernote.md
    - Snagit & Jing: embedding/jing.md
  - Install & Config: getting-started.md
  - Extensions:
    - Admonition: extensions/admonition.md
    - CodeHilite: extensions/codehilite.md
    - Footnotes: extensions/footnotes.md
    - Metadata: extensions/metadata.md
    - Permalinks: extensions/permalinks.md
    - PyMdown: extensions/pymdown.md
  - Specimen: specimen.md
  - Customization: customization.md
  #- Release notes: release-notes.md
  #- Contributing: contributing.md
  #- License: license.md

# Google Analytics
# google_analytics:
#   - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
#   - auto
