# Project information
site_name: MkDocs Material Components
site_description: A Material Design Components theme for MkDocs
site_author: Joshua Burnett
site_url: http://yakworks.github.io/mkdocs-material-components/

# Repository
repo_name: yakworks/mkdocs-material-components
repo_url: https://github.com/yakworks/mkdocs-material-components
edit_uri: edit/material-components-web/docs/

# Copyright
copyright: 'Copyright &copy; 2016 - 2017 Martin Donath, changes by Joshua Burnett'

# Theme directory
theme_dir: material
# theme: 'material-components' # Use this one if not developing here

# Options
extra:
  version: 1.10.5
  # logo: images/logo_white.png
  #
  # use console.log(btoa('some-password')) in chrome console to generate.
  # If this is set js will force a div overlay over all the page content.
  # this is NOT security. A user can always just use the debubg console and remove the overlay div or just look at the html source for the page
  # password: 'c2VjcmV0' # <- resolves to 'secret'
  #
  # adds <meta name="robots" content="noindex,nofollow"> to keep search engines from indexing this
  # noindex: true
  #
  # font:
  #   text: 'Open Sans'
  #   code: 'Ubuntu Mono'
  # feature:
  #  tabs: false
  palette:
    primary: 'blue grey'
    accent: indigo
  social:
    - type: globe
      link: http://struct.cc
    - type: github-alt
      link: https://github.com/9ci
    - type: twitter
      link: https://twitter.com/9ci
    - type: linkedin
      link: https://de.linkedin.com/in/greenbill

# Extensions
markdown_extensions:
  - pymdownx.extra # replacement for markdown.extensions.extra see https://facelessuser.github.io/pymdown-extensions/extensions/extra/
  - pymdownx.github # untility to add a bunch of others
  - markdown.extensions.sane_lists
  - markdown.extensions.admonition
  - markdown.extensions.codehilite #(guess_lang=false)
  - markdown.extensions.meta
  - markdown.extensions.toc(permalink=true)
  - markdown_include.include:
      base_path: 'docs'
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.critic

  # the following are included in the ppymdown.extra and pymdown.github
  # - markdown.extensions.def_list
  # - markdown.extensions.footnotes
  # - markdown.extensions.abbr
  # - pymdownx.betterem(smart_enable=all)
  # - pymdownx.emoji:
  #    emoji_index: !!python/name:pymdownx.emoji.gemoji
  # - pymdownx.magiclink
  # - pymdownx.superfences
  # - pymdownx.tilde

# Page tree
pages:
  - Intro: index.md
  - Cheat Sheet: cheat-sheet.md
  - Admonitions, callouts, sidebars: blocks.md
  - Embedding web apps:
    - Excel: embedding/excel.md
    - Lucid Charts : embedding/lucid.md
    - Evernote: embedding/evernote.md
    - Snagit & Jing: embedding/jing.md
    - Github: embedding/github.md
  - Install & Config: getting-started.md
  - Extensions:
    - Admonition: extensions/admonition.md
    - CodeHilite: extensions/codehilite.md
    - Footnotes: extensions/footnotes.md
    - Metadata: extensions/metadata.md
    - Permalinks: extensions/permalinks.md
    - PyMdown: extensions/pymdown.md
  - Specimen: specimen.md
  - Customization: customization.md
  #- Release notes: release-notes.md
  #- Contributing: contributing.md
  #- License: license.md

dev_addr: 0.0.0.0:8000

# Google Analytics
# google_analytics:
#   - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
#   - auto
