name: Add a translation
description: Missing support for your language? Add a translation
title: Add translations for ...
labels:
  - change request
body:

  - type: markdown
    attributes:
      value: >-
        **Important**: Before creating a new translation, please check if
        Material for MkDocs already supports your language. Review the list of
        [available languages](https://squidfunk.github.io/mkdocs-material/setup/changing-the-language/#site-language),
        pick your language to add new or improve existing translations.

  - type: textarea
    id: translations
    attributes:
      label: Translations
      description: >-
        Please translate the labels on the right. For new languages, translate
        each line. For existing languages, only translate lines containing the
        :arrow_left: icon and remove the icon before submitting.
        [More](https://squidfunk.github.io/mkdocs-material/contributing/adding-translations/#translations_1)
      value: |-
        {% macro t(key) %}{{ {
  "language": "mk",
  "action.edit": "Уредете ја оваа страница",
  "action.skip": "Прескокнете до содржината",
  "action.view": "Прикажи го изворот на оваа страница",
  "announce.dismiss": "Не го прикажувај ова повторно",
  "blog.archive": "Архива",
  "blog.categories": "Категории",
  "blog.categories.in": "во",
  "blog.continue": "Продолжи со читање",
  "blog.draft": "Нацрт",
  "blog.index": "Назад кон индекс",
  "blog.meta": "Метадата",
  "blog.references": "Поврзани линкови",
  "clipboard.copy": "Копирај во таблата",
  "clipboard.copied": "Копирано",
  "consent.accept": "Прифати",
  "consent.manage": "Прилагодување со поставките",
  "consent.reject": "Одбиј",
  "footer": "Подножје",
  "footer.next": "Следно",
  "footer.previous": "Претходно",
  "header": "Заглавје",
  "meta.comments": "Коментари",
  "meta.source": "Извор",
  "nav": "Наслов за навигација",
  "readtime.one": "1 min читање",
  "readtime.other": "# min читање",
  "rss.created": "RSS извор",
  "rss.updated": "RSS извор на ажурирана содржина",
  "search": "Пребарување",
  "search.placeholder": "Пребарување",
  "search.share": "Сподели",
  "search.reset": "Чисти",
  "search.result.initializer": "Иницијализирање на пребарувањето",
  "search.result.placeholder": "Напишете за да започнете со пребарување",
  "search.result.none": "Нема соодветни документи",
  "search.result.one": "1 документ што се совпаѓа",
  "search.result.other": "# соодветни документи",
  "search.result.more.one": "Уште 1 на оваа страница",
  "search.result.more.other": "Уште # на оваа страница",
  "search.result.term.missing": "Недостасува",
  "select.language": "Изберете јазик",
  "select.version": "Изберете верзија",
  "source": "Одете до складиштето",
  "source.file.contributors": "Соработници",
  "source.file.date.created": "Создаден",
  "source.file.date.updated": "Последно ажурирање",
  "tabs": "Јазичиња",
  "toc": "Содржина",
  "top": "Вратете се на почетокот"
}[key] }}{% endmacro %}
      render: Jinja
    validations:
      required: true

  - type: input
    id: country-flag
    attributes:
      label: Country flag
      description: >-
        This field is optional. Please add the flag of the country when adding a
        new language. Go to our [emoji search](https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#search)
        and enter `flag` to find all available shortcodes. If your flag is not
        included, please choose the most appropriate available flag.
        [More](https://squidfunk.github.io/mkdocs-material/contributing/adding-translations/#country-flag)
      placeholder: |-
        Country flag shortcode, e.g. :flag_en:

  - type: checkboxes
    id: checklist
    attributes:
      label: Before submitting
      description: >-
        Please ensure that your translation fulfills the following requirements.
      options:
        - label: >-
            I've checked the list of [available languages](https://squidfunk.github.io/mkdocs-material/setup/changing-the-language/#site-language) for existing translations.
          required: true
        - label: >-
            I assure that the translations are accurate to the best of my knowledge.
          required: true
        - label: >-
            __Optional__: I want to integrate this translation myself and create a
            pull request following the [contribution guide](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md).
